#version original del codigo:
print("Original:")
print("    *    "*2) #*2 rovoca que se repita la cadena
print("   * *   "*2)
print("  *   *  "*2)
print(" *     * "*2)
print("***   ***"*2)
print("  *   *  "*2)
print("  *   *  "*2)
print("  *****  "*2)
#version con menos prints con salto de renglon \n
print("Original con menos prints:")
print("\n    *    \n   * *   \n  *   *  \n *     * \n***   ***\n  *   *  \n  *   *  \n  *****"*2)
print("Aumentado al 2ble:")
###################
print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("******     ******"*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *******     "*2)
print("Aumentado al 2ble con menos prints:")
print("\n        *        \n       * *       \n      *   *      \n     *     *     \n    *       *    \n   *         *   \n  *           *  \n *             * \n******     ******\n     *     *     \n     *     *     \n     *     *     \n     *     *     \n     *     *     \n     *     *     \n     *******     \n"*2)